# Generated by Django 2.2.2 on 2019-07-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registereduser_has_dual_account'),
        ('or_extra1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_desc', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('duration_in_months', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_plan', to='or_extra1.SubscriptionPlan')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_ruser', to='accounts.RegisteredUser')),
            ],
        ),
    ]
