# Generated by Django 2.2.2 on 2019-07-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190710_1422'),
        ('or_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_serial_no', models.PositiveIntegerField(default=1)),
                ('video_status', models.CharField(blank=True, choices=[('1', 'Not Played'), ('2', 'Completed'), ('3', 'In Progress')], default='Not Played', max_length=20)),
                ('video_watch_duration', models.PositiveIntegerField(default=0)),
                ('video_total_duration', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vwl_course', to='or_accounts.Course')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vwl_mentee', to='accounts.RegisteredUser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vwl_video', to='or_accounts.CourseVideo')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'Start'), ('2', 'In Progress'), ('3', 'Finished'), ('4', 'Refund Requested'), ('5', 'Refunded')], default='Start', max_length=20)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('duration_completed', models.PositiveIntegerField(default=0)),
                ('duration_left', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_reg_course', to='or_accounts.Course')),
                ('last_video_watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_reg_video', to='or_accounts.CourseVideo')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_reg_mentee', to='accounts.RegisteredUser')),
            ],
        ),
    ]
