# Generated by Django 2.2.2 on 2019-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteecourseregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Start'), ('2', 'In Progress'), ('3', 'Completed'), ('4', 'Refund Requested'), ('5', 'Refunded')], default='Start', max_length=20),
        ),
        migrations.AlterField(
            model_name='videowatchlist',
            name='video_status',
            field=models.CharField(blank=True, choices=[('1', 'Not Played'), ('2', 'In Progress'), ('3', 'Completed')], default='Not Played', max_length=20),
        ),
    ]
