# Generated by Django 2.2.2 on 2019-07-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registereduser_has_dual_account'),
        ('or_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='mentee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cert_mentee', to='accounts.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
