# Generated by Django 2.2.2 on 2019-07-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floowing_from', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='mentee_panel/profile')),
                ('age', models.PositiveIntegerField(default=0)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('alt_mobile_country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('alt_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=10, null=True)),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('building_num', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('login_type', models.CharField(choices=[('1', 'Normal'), ('2', 'Facebook'), ('3', 'Google')], max_length=10)),
                ('social_id', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(choices=[('1', 'Android'), ('2', 'Ios'), ('3', 'Web')], max_length=10)),
                ('device_token', models.CharField(blank=True, max_length=200, null=True)),
                ('user_type', models.CharField(choices=[('1', 'Mentee'), ('2', 'Mentor')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.FileField(blank=True, null=True, upload_to='mentor_panel/declaration')),
                ('experience', models.CharField(blank=True, max_length=80, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
