# Generated by Django 2.2.2 on 2019-07-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('or_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_course', to='or_accounts.Course'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_user', to='accounts.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ru_background', to='or_accounts.Background'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ru_category', to='or_accounts.Category'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followinglist',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_mentee', to='accounts.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='followinglist',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_mentor', to='accounts.RegisteredUser'),
        ),
    ]
