# Generated by Django 2.2.2 on 2019-07-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190710_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
