# Generated by Django 2.2.2 on 2019-07-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190711_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='has_dual_account',
            field=models.BooleanField(default=False),
        ),
    ]
