# Generated by Django 2.2.2 on 2019-07-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('or_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_user4', to='accounts.RegisteredUser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_video', to='or_accounts.CourseVideo')),
            ],
        ),
        migrations.CreateModel(
            name='MentorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_mentor', to='accounts.RegisteredUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_user3', to='accounts.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_course', to='or_accounts.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_user', to='accounts.RegisteredUser')),
            ],
        ),
    ]
